In [ ]:
!pip install d2l

In [1]:
import numpy as np
import tensorflow as tf
from d2l import tensorflow as d2l

In [2]:
true_w = tf.constant([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [3]:
def load_array(data_arrays, batch_size, is_train=True):  #@save"""Construct a TensorFlow data iterator."""
    dataset = tf.data.Dataset.from_tensor_slices(data_arrays)
    if is_train:
        dataset = dataset.shuffle(buffer_size=1000)
    dataset = dataset.batch(batch_size)
    return dataset

batch_size = 10
data_iter = load_array((features, labels), batch_size)

In [4]:
next(iter(data_iter))

(<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
 array([[ 1.3783151 , -2.401884  ],
        [ 0.11294492, -1.1786999 ],
        [-2.8305123 ,  0.17662422],
        [-0.80549836, -0.09430042],
        [ 0.7971161 , -0.40427148],
        [-0.7145923 ,  0.6085617 ],
        [ 0.6802494 , -1.6813197 ],
        [ 1.3297487 , -0.44246575],
        [ 1.1269135 ,  0.21707377],
        [-1.6830164 , -1.7682842 ]], dtype=float32)>,
 <tf.Tensor: shape=(10, 1), dtype=float32, numpy=
 array([[15.135514 ],
        [ 8.425373 ],
        [-2.0680912],
        [ 2.9216757],
        [ 7.168339 ],
        [ 0.7062099],
        [11.278441 ],
        [ 8.372044 ],
        [ 5.713813 ],
        [ 6.8507295]], dtype=float32)>)

## Defining The Model

In [5]:
# `keras` is the high-level API for TensorFlow
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1))

In [6]:
initializer = tf.initializers.RandomNormal(stddev=0.01)
net = tf.keras.Sequential()
net.add(tf.keras.layers.Dense(1, kernel_initializer=initializer))

In [7]:
loss = tf.keras.losses.MeanSquaredError()

In [8]:
trainer = tf.keras.optimizers.SGD(learning_rate=0.03)

In [9]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        with tf.GradientTape() as tape:
            l = loss(net(X, training=True), y)
        grads = tape.gradient(l, net.trainable_variables)
        trainer.apply_gradients(zip(grads, net.trainable_variables))
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

epoch 1, loss 0.000266
epoch 2, loss 0.000100
epoch 3, loss 0.000100


In [10]:
w = net.get_weights()[0]
print('error in estimating w', true_w - tf.reshape(w, true_w.shape))
b = net.get_weights()[1]
print('error in estimating b', true_b - b)

error in estimating w tf.Tensor([-0.00037718  0.00020766], shape=(2,), dtype=float32)
error in estimating b [-0.00142431]
